version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  Specimen-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./tests/Specimen.postman_collection.json
          environment: ./tests/environments/Testing.postman_environment.json


workflows:
  version: 2
  test:
    jobs:
      - Specimen-collection-run



